import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import { useContext, useEffect } from 'react';
import VotingContext from '../context/voting/VotingContext';
import { useRouter } from 'next/router';

const Home = () => {
	const votingContext = useContext(VotingContext);
	const router = useRouter();

	const {
		connectToNear,
		wallet,
		loadContract,
		getBalance,
		checkIfSignedIn,
		isSignedIn,
		login,
		contract,
	} = votingContext;

	// Establish a connection to the NEAR blockchain on component mount
	useEffect(() => {
		connectToNear();
		//eslint-disable-next-line
	}, []);

	// Initialize the contract object when the wallet is available
	useEffect(() => {
		if (wallet) {
			loadContract(wallet);

			// We can get the account balance of a user through the wallet
			// Since this is requesting data from the blockchain, the method returns a Promise
			getBalance(wallet);
		}
		//eslint-disable-next-line
	}, [wallet]);

	useEffect(() => {
		checkIfSignedIn(wallet, contract);

		if (isSignedIn) {
			//router.push('/dashboard');
		}
		//eslint-disable-next-line
	}, [isSignedIn, wallet, contract]);

	return (
		<div>
			<Head>
				<title>Voting Dapp</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main className='container mx-auto'>
				<div className='mt-8'>
					<nav className=' flex justify-between items-center'>
						<Link href='/'>
							<a href='#' className='text-2xl font-bold hover:text-[#4B60B0]'>
								Voting Dapp
							</a>
						</Link>
						<button
							onClick={() => {
								isSignedIn ? router.push('/dashboard') : login(wallet, router);
							}}
							className='bg-[#4B60B0] flex items-center justify-center text-white rounded-md uppercase px-5 py-3 hover:bg-slate-900'
						>
							{isSignedIn ? 'dashboard' : 'sign in'}
						</button>
					</nav>
					<section className='flex items-center justify-between mt-32'>
						<div className='flex flex-col items-center'>
							<h3 className='text-4xl font-bold text-[#4B60B0] my-4'>
								Start voting in minutes
							</h3>
							<p className='text-base text-gray-400 mb-4 text-left'>
								Vote for your preferred candidate
							</p>
							<button
								onClick={() => login(wallet, router)}
								className='bg-[#4B60B0] flex items-center justify-center text-white rounded-md uppercase px-5 py-3 hover:bg-slate-900'
							>
								get started
							</button>
						</div>
						<div>
							<Image src='/images/1.png' alt='' height='500' width='600' />
						</div>
					</section>
				</div>
			</main>
		</div>
	);
};

export default Home;
